### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by eric48906** [nightclubs/funcaptcha-solver#2]
The error is:

Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format

What am I doing wrong?

**Comment by eric48906** [comment]
Upon logging it, it now says

`b'{"error":"DENIED ACCESS"}'` which is probably causing the error but I still have no idea how to fix this

**Comment by nightclubs** [comment]
> Upon logging it, it now says
> 
> `b'{"error":"DENIED ACCESS"}'` which is probably causing the error but I still have no idea how to fix this

yes, I am receiving the same error im working on a fix please be patient.

**Comment by nightclubs** [comment]
> The error is:
> 
> Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format
> 
> What am I doing wrong?

this is because when the game audio was "started" it never actually grabbed anything so it just made a random .wav file that was corrupted.
